POST http://localhost:8001/api/auth
content-type: application/json

{
    "email": "carlos@expert.org",
    "password": "12345"
}

###
POST http://localhost:8001/api/auth
content-type: application/json

{
    "email": "carlos@expert.org",
    "password": "12345"
}
